"""Mock product catalog for bio materials.

Each product includes a Scientific Score derived from publication citation data,
following the Zageno model of evidence-based product comparison.

scientific_score: 1.0–5.0  (weighted from citation_count and reproducibility reports)
citation_count:   number of peer-reviewed publications citing this specific product/catalog #
reproducibility_flag: True if product has known lot-to-lot variability issues in literature
"""

PRODUCTS = [
    {
        "id": "P001",
        "name": "Matrigel Growth Factor Reduced (GFR), Phenol Red-Free",
        "supplier": "Corning",
        "catalog_number": "354230",
        "description": "Basement membrane matrix for 3D cell culture and organoids",
        "grade": "research",
        "volume_ml": 10,
        "price_usd": 189.00,
        "unit": "10mL",
        "storage": "-20°C",
        "shipping": "dry ice",
        "lead_time_days": 3,
        "requires_cold_chain": True,
        "applications": ["3D culture", "organoids", "invasion assay"],
        "in_stock": True,
        "scientific_score": 4.8,
        "citation_count": 12400,
        "reproducibility_flag": False,
        "community_note": "Gold standard for organoid culture; GFR formulation preferred for signalling studies.",
    },
    {
        "id": "P002",
        "name": "Matrigel Basement Membrane Matrix",
        "supplier": "Fisher Scientific",
        "catalog_number": "CB-40234",
        "description": "Solubilized basement membrane from Engelbreth-Holm-Swarm mouse sarcoma",
        "grade": "research",
        "volume_ml": 10,
        "price_usd": 175.00,
        "unit": "10mL",
        "storage": "-20°C",
        "shipping": "dry ice",
        "lead_time_days": 5,
        "requires_cold_chain": True,
        "applications": ["3D culture", "organoids", "angiogenesis"],
        "in_stock": True,
        "scientific_score": 3.9,
        "citation_count": 3100,
        "reproducibility_flag": True,
        "community_note": "Lower citation density; some reports of lot-to-lot protein composition variability.",
    },
    {
        "id": "P003",
        "name": "BSA (Bovine Serum Albumin), Fraction V, ≥98%",
        "supplier": "Sigma-Aldrich",
        "catalog_number": "A2153",
        "description": "Bovine serum albumin for western blot blocking and protein assays",
        "grade": "western blot",
        "weight_g": 100,
        "price_usd": 52.00,
        "unit": "100g",
        "storage": "4°C",
        "shipping": "ambient",
        "lead_time_days": 2,
        "requires_cold_chain": False,
        "applications": ["western blot", "ELISA", "protein assay", "cell culture"],
        "in_stock": True,
        "scientific_score": 4.6,
        "citation_count": 28700,
        "reproducibility_flag": False,
        "community_note": "Most widely cited BSA in western blot and ELISA protocols; highly consistent across lots.",
    },
    {
        "id": "P004",
        "name": "BSA (Bovine Serum Albumin), Molecular Biology Grade",
        "supplier": "VWR",
        "catalog_number": "0332-100G",
        "description": "Nuclease-free BSA for molecular biology applications",
        "grade": "molecular biology",
        "weight_g": 100,
        "price_usd": 61.00,
        "unit": "100g",
        "storage": "4°C",
        "shipping": "ambient",
        "lead_time_days": 3,
        "requires_cold_chain": False,
        "applications": ["western blot", "PCR", "restriction digest"],
        "in_stock": True,
        "scientific_score": 4.1,
        "citation_count": 5200,
        "reproducibility_flag": False,
        "community_note": "Nuclease-free certification makes it the preferred choice for PCR and cloning workflows.",
    },
    {
        "id": "P005",
        "name": "Fetal Bovine Serum (FBS), Heat Inactivated",
        "supplier": "Thermo Fisher",
        "catalog_number": "10082147",
        "description": "US origin FBS, heat inactivated at 56°C for 30 min",
        "grade": "cell culture",
        "volume_ml": 500,
        "price_usd": 298.00,
        "unit": "500mL",
        "storage": "-20°C",
        "shipping": "dry ice",
        "lead_time_days": 4,
        "requires_cold_chain": True,
        "applications": ["cell culture", "primary cells", "hybridoma"],
        "in_stock": True,
        "scientific_score": 4.7,
        "citation_count": 41000,
        "reproducibility_flag": False,
        "community_note": "US-origin traceability and strict endotoxin testing make this the benchmark FBS for primary cell culture.",
    },
    {
        "id": "P006",
        "name": "DMEM High Glucose, Pyruvate",
        "supplier": "Gibco",
        "catalog_number": "11995065",
        "description": "Dulbecco's Modified Eagle Medium with 4500mg/L glucose",
        "grade": "cell culture",
        "volume_ml": 500,
        "price_usd": 28.00,
        "unit": "500mL",
        "storage": "4°C",
        "shipping": "ambient",
        "lead_time_days": 2,
        "requires_cold_chain": False,
        "applications": ["cell culture", "mammalian cells"],
        "in_stock": True,
        "scientific_score": 4.9,
        "citation_count": 67000,
        "reproducibility_flag": False,
        "community_note": "Most cited basal medium in mammalian cell culture literature; Gibco quality control is industry reference.",
    },
    {
        "id": "P007",
        "name": "Collagen Type I, Rat Tail",
        "supplier": "Corning",
        "catalog_number": "354236",
        "description": "High concentration rat tail collagen for 3D hydrogels and coatings",
        "grade": "research",
        "volume_ml": 20,
        "price_usd": 145.00,
        "unit": "20mL",
        "storage": "4°C",
        "shipping": "cold pack",
        "lead_time_days": 4,
        "requires_cold_chain": True,
        "applications": ["3D culture", "hydrogel", "coating", "organoids"],
        "in_stock": True,
        "scientific_score": 4.5,
        "citation_count": 9800,
        "reproducibility_flag": False,
        "community_note": "High protein concentration (>3 mg/mL) enables precise gelation titration; widely used in mechanobiology.",
    },
    {
        "id": "P008",
        "name": "Trypsin-EDTA 0.25%",
        "supplier": "Sigma-Aldrich",
        "catalog_number": "T4049",
        "description": "Sterile-filtered trypsin-EDTA solution for cell detachment",
        "grade": "cell culture",
        "volume_ml": 100,
        "price_usd": 38.00,
        "unit": "100mL",
        "storage": "-20°C",
        "shipping": "dry ice",
        "lead_time_days": 2,
        "requires_cold_chain": True,
        "applications": ["cell culture", "passaging"],
        "in_stock": True,
        "scientific_score": 4.3,
        "citation_count": 15600,
        "reproducibility_flag": False,
        "community_note": "Standard 0.25% formulation; consistently cited in passaging protocols across cell lines.",
    },
]
